build:
# 	gcc -std=c99 -Wall -Wextra -Wpedantic -O2 -shared -o bin/sax_json.dll -Wl,--out-implib,bin/libsax_json.a sax_json.c
	cl /c /W4 /nologo /O2 /Zi /Fdbin\sax_json.pdb /Fo:bin\sax_json.obj sax_json.c